root: ./docs

structure:
  readme: README.md
  summary: SUMMARY.md

title: DI Protocol Documentation
description: Comprehensive documentation for the DI protocol

integrations:
  github:
    owner: DINetworks
    repo: MetaTx-Contracts
    branch: main

format:
  markdown:
    mermaid: true